# Generated by Django 5.2.1 on 2025-05-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
